services:
  homecareexperts-next:
    container_name: homecareexperts-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000

    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/homecareexperts-next

    working_dir: /usr/src/homecareexperts-next

    networks:
      - client-network

    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# ==================================================================================================================

# homecareexperts-next: localhost:4000 <=> container:3000
# homecareexperts-api:  localhost:4001 <=> container:3005
# homecareexperts-batch: localhost:4002 <=> container:3006

# docker-compose up -d
# docker-compose stop
# docker-compose start
# docker-compose restart
# docker-compose stop && docker-compose rm -f
